package enums;

public enum Tag {
    AARAKOCRA, BULLYWUG, DEMON, DEVIL, ELF, GITH, GNOLL, GNOME, GOBLINOID, GRIMLOCK, HUMAN, KENKU, KOBOLD, KUO_TOA, LIZARDFOLK, MERFOLK, ORC, QUAGGOTH, SAHUAGIN, SHAPECHANGER, THRI_KREEN, TITAN, TROGLODYTE, YUAN_TI, YUGOLOTH
}
